### ISSUE TITLE
编程工具可以添加aws提供的codewhisper

### ISSUE THREAD

**Issue by Misaka19042** [ikaijua/Awesome-AITools#1]
aws开放了免费给个人使用的ai编程辅助工具codewhisper，在各种IDE的插件中可以安装,支持15种语言, including Python, Java, and JavaScript等。只需要按照流程注册一个aws builder账号即可。

附上相关链接：
https://aws.amazon.com/cn/codewhisperer/?nc1=h_ls

**Comment by ikaijua** [comment]
已添加 https://github.com/ikaijua/Awesome-AITools/commit/4abc24bb858a6af91bf22f301dcb3896c273b1ea
