### ISSUE TITLE
编程工具：CodeGeeX

### ISSUE THREAD

**Issue by RaysLinn** [ikaijua/Awesome-AITools#3]
官网：[https://codegeex.cn/](https://codegeex.cn/)

清华大学鹏城实验室的项目。

免费。

已可用于VScode和JB，但会与Copilot冲突。

**Comment by ikaijua** [comment]
已添加 。https://github.com/ikaijua/Awesome-AITools/commit/909970f6b556cf6d73a9dc42dd39f9977b8458ff
