### ISSUE TITLE
免费文本转语音 1000+声音

### ISSUE THREAD

**Issue by ALEXuH** [ikaijua/Awesome-AITools#31]
url： https://www.ttson.cn        https://acgn.ttson.cn

免费。

提供超过160种声音选项 美真人配音选择，包含主流的小帅 小美 微软的一些语音

如果你是二次元游戏迷之类网站还提供超过1000+的动漫游戏角色的声音

网站可以提供api

**Comment by ikaijua** [comment]
已添加
https://github.com/ikaijua/Awesome-AITools/commit/d4d27c825a26fb26b67d57776d04efc0d54c1d89
